### ISSUE TITLE
Problema con la configuración de los tooltips en Chart.js

### ISSUE THREAD

**Issue by MiguelOAlv** [MiguelOAlv/WoWTokenPrice#8]
No logro configurar los tooltips correctamente en Chart.js. He intentado modificar las opciones de configuración según la documentación oficial, pero los tooltips no aparecen como se espera al pasar el ratón sobre los puntos del gráfico.

**Comment by pascu01** [comment]
Los tooltips deberían aparecer al pasar el ratón sobre los puntos del gráfico, mostrando información relevante como etiquetas y valores.
:D
